### ISSUE TITLE
Automate and/or sanity check A2_REALTIME

### ISSUE THREAD

**Issue by olofson** [olofson/audiality2#201]
Some of the tools and examples grab the A2_REALTIME flag from the selected driver, which is really the only correct way to use it, except possibly with the 'buffer' driver. (If a2_Run() is called from a different thread, A2_REALTIME should be used!)

I have a feeling this should be automatic somehow, or at least be sanity checked, because Bad Things(TM) will likely happen if a state is set up for non-realtime operation when using a realtime driver.

Not sure if that flag should even be in the public API in the form it is now.

**Comment by v3n** [comment]
Gotcha, thanks. So it looks like my use of A2_REALTIME is correct, which probably puts the skipping/underflow I’m experiencing in the hands of the AudioToolkit set up. Good to know where to start debugging. 

Thanks!
— v3n
