### ISSUE TITLE
This is the C64 'SID' replacement.

### ISSUE THREAD

**Issue by clort81** [olofson/audiality2#348]
Next to sunvox this is the greatest chiptune maker ever.

That is all.

You do amazing stuff.

**Comment by olofson** [comment]
Thank you, that's a huge compliment! SunVox is really cool.

Also, sorry I haven't been active around here in ages - and that I didn't see your ticket until just now! (GH notifications are weird...)

However, as I'm now a full time games audio programmer, and keep hitting limitations I did not expect to see in the industry standard solutions, I'm considering whipping Audiality 2 into shape, initially intended as an extension for popular game audio engines, so devs can keep their toolchains, integrations etc. Also, VST for DAWs; there should be a ticket for that already.
